image: kopaxgroup/node10-jdk8-flyway4-sonarscanner2-docker17-debian

before_script:
  - npx -p rollup-umd-scripts scripts-ci before-script

stages:
  - build
  - test
  - release
  - deploy

# Job: Build
build:
  stage: build
  script:
    - npx -p rollup-umd-scripts scripts-ci build
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    when: on_success
    name: "${CI_PROJECT_PATH}-${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 1 hour
    paths:
      - .
  only:
    - tags
    - dev
    - master
  tags:
    - docker

# Job: Test
test:
  stage: test
  coverage: '/All files[^|]*\|\s*[\d.]*\s*\|\s*[\d.]*\s*\|\s*[\d.]*\s*\|\s*([\d.]*)\s*\|\s*/'
  script:
    - npx -p rollup-umd-scripts scripts-ci test
  dependencies:
    - build
  only:
    - tags
    - dev
    - master
  tags:
    - docker

.node:8:
  image: node:8
  stage: test
  dependencies:
    - build
  script:
    - npx -p rollup-umd-scripts scripts-ci test
  only:
    - dev
    - master
  tags:
    - docker

.node:9:
  image: node:9
  stage: test
  dependencies:
    - build
  script:
    - npx -p rollup-umd-scripts scripts-ci test
  only:
    - dev
    - master
  tags:
    - docker

# Job: Release
release:
  stage: release
  script:
    - npx -p rollup-umd-scripts scripts-ci release
  dependencies:
    - build
  only:
    - master
  tags:
    - docker

# Pages
pages:
  stage: deploy
  script:
    - npx -p rollup-umd-scripts scripts-ci deploy
  artifacts:
    paths:
    - public
  only:
    - tags
  tags:
    - docker
